spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_MAIL}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

mail:
  info:
    receiver: ${RECEIVER_MAIL}

scheduled:
  cron:
    morning-time: 0 0 19 * * *
    evening-time: ${EVENING_SEND_TIME}